# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            François Pitié
tagline:          Researcher in Signal Processing for Media Post-Production
description:      'Researcher <br> in Signal Processing <br> for Media Post-Production'
url:              https://francois.pitie.net
enforce_ssl: 	  francois.pitie.net
baseurl:          /

author:
  name:           'François Pitié'
  url:            https://francois.pitie.net

gems:
  - jekyll-sitemap
  
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/frcs
  projects:       https://github.com/frcs
