# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            François Pitié
tagline:          Ussher Assistant Professor in Media Signal Processing
description:      'Ussher Assistant Professor <br> in Media Signal Processing'
url:              https://francois.pitie.net
enforce_ssl: 	  francois.pitie.net
baseurl:          /

author:
  name:           'François Pitié'
  url:            https://francois.pitie.net

gems:
  - jekyll-sitemap
  
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/frcs
  projects:       https://github.com/frcs

comments: false
